apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: springtrader
    docker:
      target: runner
      cacheFrom:
        - harbor.toolchain.lead.prod.liatr.io/flywheel/springtrader-builder:latest
        - harbor.toolchain.lead.prod.liatr.io/flywheel/springtrader-runner:latest
  - image: sqlfdb
    docker:
      target: sqlfdb
      cacheFrom:
        - harbor.toolchain.lead.prod.liatr.io/flywheel/springtrader-builder:latest
        - harbor.toolchain.lead.prod.liatr.io/flywheel/springtrader-runner:latest
  local: {}

