{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-credentials
data:
  "mongodb.json": |
    {
      "username": {{ .Values.database.username | quote }},
      "password": {{ .Values.database.password | quote }}
    }
{{- end }}
