{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-credentials
data:
  "mongodb.json": |
    {
      "username": "app",
      "password": "password"
    }
{{- end }}
